### PR TITLE
The Russian translation was improved.

### PR DESCRIPTION
**Pull request by DimaKoz**

### CODE REVIEW

**Comment by vlet** [comment]
Thanks for corrections, but I don't like 10.4 translation.

**Comment by vlet** [comment]
«Текущие эксперименты Chrome с QUIC (смотри раздел 12.1) отчасти уменьшают долю HTTP/2.» ?

**Comment by DimaKoz** [comment]
@vlet Why not. Your translation section 10.4 is better than my translation. I added your translation.
@bagder Daniel, please accept my request.

**Comment by bagder** [comment]
Thanks for this @DimaKoz!

@vlet, do I have your approval with the update?

**Comment by vlet** [comment]
@bagder, sure.

**Pull request merged**
