### PR TITLE
(turkish) Some updates

### PR DESCRIPTION
**Pull request by zynpsnltrk**
Hello @bagder , there is only a correction and some changes.

### CODE REVIEW

**Comment by bagder** [comment]
"a correction and some changes" and yet a very large amount of commits? Did you do more commits than you intended to? Also, there are conflicts here which indicates the latter perhaps?

**Comment by zynpsnltrk** [comment]
At odd times to make it more understandable I am writing the Turkish expressions more smoothly by reading it again and again @bagder

**Comment by bagder** [comment]
That's great, but this still looks like a mistake. There are still conflicts in this branch!

**Comment by zynpsnltrk** [comment]
Yes my mistake, is there a problem now? @bagder

**Comment by bagder** [comment]
The same problem remains, but now you've added a commit to the branch. Please rebase your working branch on top of our master branch, then force-push the result here.

**Comment by bagder** [comment]
I manually squashed and rebased your work on top of master and pushed. Please check it out and file updates if I screwed up anything!

**Pull request closed without merging**
