### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by olegstepura**
More details: http://tsya.ru/

### CODE REVIEW

**Comment by bagder** [comment]
please review, @vlet

**Comment by vlet** [comment]
Ok, thanks

**Comment by bagder** [comment]
Is that a confirmation that the fix is fine?

**Comment by vlet** [comment]
Yes, fix is fine.

**Comment by bagder** [comment]
Thanks!

**Comment by olegstepura** [comment]
:+1:

**Pull request closed without merging**
