### PR TITLE
Added remaining untranslated content, improved overall readability, spellcheck

### PR DESCRIPTION
**Pull request by fantuz**

### CODE REVIEW

**Comment by fantuz** [comment]
i didn't "cherry picked" commits, but now you CAN trust it :+1:

**Comment by bagder** [comment]
But it still has a merge conflict, how can that be?

**Comment by fantuz** [comment]
Hello, I have no console access ATM.
Since the beginning I allowed you full r/w permissions on my fork, just in
case.

Have a look if you got two minutes, sorry for the inconvenience :/

**Comment by bagder** [comment]
Unfortunately that didn't help me much, your last commits in your tree are also confusing.

How about you do this. Start over fresh:
1. copy your entire http2-explained tree to a new name for safe-keeping
2. remove your github fork
3. create a new fork
4. clone this new fork - now completely in sync with upstream
5. create a branch in your fork, one branch for every series of changes
6. copy the contents from your backed up italian updates into the fresh fork and branch
7. commit the updates
8. push them in your repo and branch
9. make a new pull request from there.

**Comment by fantuz** [comment]
I believe my PR was created before the addition of Persian language.

Should be green now.

Otherwise I will really start fresh as you suggest.
I just want to make sure that you can incorporate the missing Italian objects added by these commits

. :+1:

**Comment by bagder** [comment]
The problem is that you keep doing all your changes in the same branch so it will continue to cause conflicts. The Persian merge should *not* cause conflicts with your updates since they are totally independent. They caused conflicts because your PR here still tries to merge commits from your previous work since you still have them in your branch - although those changes are already merged.

It is way easier if you do a unique branch for each separate PR you do, and once the PR is merged you can delete that branch...

**Pull request closed without merging**
